# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

target 'AlamofireObjectMapperDemo' do
  use_frameworks!

	pod 'ObjectMapper', '~> 2.2.0'
    pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :tag => '4.3.0'
    pod 'RealmSwift'

  # Pods for AlamofireObjectMapperDemo

  target 'AlamofireObjectMapperDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlamofireObjectMapperDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
